version: '3.8'

services:

  jenkins:
    image: docker.io/mguazzardo/pipe-seg
    ports:
      - "8080:8080"
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"